name: OnePlus Kernel Build

on:
  workflow_dispatch:
    inputs:
      manifest_files:
        description: '选择内核清单（多个值用逗号分隔）'
        required: true
        type: string
        default: 'oneplus12_v'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        manifest_file: ${{ split(github.event.inputs.manifest_files, ',') }}
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.x"

      - name: Install repo tool
        run: |
          sudo apt-get update
          sudo apt-get install repo
          mkdir kernel_workspace

      - name: Initialize and sync repo
        working-directory: kernel_workspace
        run: |
          repo init \
            -u https://github.com/OnePlusOSS/kernel_manifest.git \
            -b refs/heads/oneplus/sm8650 \
            -m ${{ matrix.manifest_file }}.xml \
            --depth=1 --repo-rev=v2.16
          repo --trace sync -c -j$(nproc) --no-tags --fail-fast

      - name: Build kernel
        working-directory: kernel_workspace
        run: |
          ../build_mksu.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: "Kernel-${{ matrix.manifest_file }}"
          path: kernel_workspace/AnyKernel3
          compression-level: 9
