name: OnePlus Kernel Build

on:
  workflow_dispatch:
    inputs:
      manifest_file:
        description: '选择设备型号'
        required: true
        type: choice
        options:
          - oneplus12_v
          - oneplus_13r
          - oneplus_ace3_pro
          - oneplus_ace3_pro_v
          - oneplus_ace5
          - oneplus_pad2_v
      enable_lto:
        description: '启用 Full LTO'
        type: boolean
        default: false
      enable_polly:
        description: '启用 Polly'
        type: boolean
        default: false
      enable_o3:
        description: '启用 O3 优化'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - uses: actions/setup-python@main
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y repo clang lld git curl patch
          mkdir kernel_workspace

      - name: Initialize repo and sync
        working-directory: kernel_workspace
        run: |
          repo init \
            -u https://github.com/OnePlusOSS/kernel_manifest.git \
            -b refs/heads/oneplus/sm8650 \
            -m ${{ github.event.inputs.manifest_file }}.xml \
            --depth=1 --repo-rev=v2.16
          repo --trace sync -c -j$(nproc) --no-tags --fail-fast

      - name: Build Kernel
        working-directory: kernel_workspace
        id: build
        run: | 
         curl -Ls https://raw.githubusercontent.com/XiaoNan7777/oneplus_susfs_ksu_kernel/main/build_mksu.sh -o build_mksu.sh
         chmod +x build_mksu.sh
         ./build_mksu.sh ${{ github.event.inputs.manifest_file }} \
                         ${{ github.event.inputs.enable_lto }} \
                         ${{ github.event.inputs.enable_polly }} \
                         ${{ github.event.inputs.enable_o3 }}

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: "AnyKernel3-${{ github.event.inputs.manifest_file }}-${{ steps.build.outputs.kernel_version }}-MKSU-${{ steps.build.outputs.ksu_version }}-SUSFS-${{ steps.build.outputs.susfs_version }}"
          path: kernel_workspace/AnyKernel3
          compression-level: 9
